# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms. 

def even_valued_fibonacci(limit)
	num =[0] #array of fibonacci numbers	 
	sum = 0 #sum of even number
	idx = 0 #index to the limit
	while(sum < limit)
		num[idx] = (idx < 2) ? (idx + 1) : (num[idx-1] + num[idx-2])
		sum = sum + num[idx] if num[idx] % 2 == 0			
		idx += 1
	end
	return sum
end

puts even_valued_fibonacci(4000000)